<% if Gem.loaded_specs.key?('rggen-devtools') %>
inherit_gem:
  rggen-devtools: config/rubocop_common.yml

inherit_from:
  - .rubocop_todo.yml
<% elsif File.exist?('rubocop_common.yml') %>
inherit_from:
  - rubocop_common.yml
  - .rubocop_todo.yml
<% else %>
inherit_from:
  - https://raw.githubusercontent.com/rggen/rggen-devtools/master/config/rubocop_common.yml
  - .rubocop_todo.yml
<% end %>
