name: Static Analysis

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Cache gems
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: gems-${{ runner.os }}-static-analysis-${{ github.sha }}
          restore-keys: |
            gems-${{ runner.os }}-static-analysis-

      - name: Install gems
        run: |
          bundle config path vendor/bundle
          bundle config set without rggen test
          bundle install

      - name: Run Rubocop
        run: |
          bundle exec rubocop --format json --out rubocop.json --config .rubocop.yml lib || :

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
